// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJiGp2-pvTzflNM83eFm5Jzq2KR5OYgOc',
    appId: '1:561116154961:web:d528e9b46cbf2a2a447c70',
    messagingSenderId: '561116154961',
    projectId: 'authentication-e8752',
    authDomain: 'authentication-e8752.firebaseapp.com',
    storageBucket: 'authentication-e8752.appspot.com',
    measurementId: 'G-XBP4GJH5XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8CGwIy2E9tMHaqiXheDjigehLhRpZ-Yc',
    appId: '1:561116154961:android:a6d85dca918f8fb1447c70',
    messagingSenderId: '561116154961',
    projectId: 'authentication-e8752',
    storageBucket: 'authentication-e8752.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_VHhTCKea5e1yhYOvyFCDHUNt9Rii2QE',
    appId: '1:561116154961:ios:8f5ee98ed55a50e7447c70',
    messagingSenderId: '561116154961',
    projectId: 'authentication-e8752',
    storageBucket: 'authentication-e8752.appspot.com',
    iosBundleId: 'com.BUMGames.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_VHhTCKea5e1yhYOvyFCDHUNt9Rii2QE',
    appId: '1:561116154961:ios:8f5ee98ed55a50e7447c70',
    messagingSenderId: '561116154961',
    projectId: 'authentication-e8752',
    storageBucket: 'authentication-e8752.appspot.com',
    iosBundleId: 'com.BUMGames.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJiGp2-pvTzflNM83eFm5Jzq2KR5OYgOc',
    appId: '1:561116154961:web:113f3502ec0d8a8a447c70',
    messagingSenderId: '561116154961',
    projectId: 'authentication-e8752',
    authDomain: 'authentication-e8752.firebaseapp.com',
    storageBucket: 'authentication-e8752.appspot.com',
    measurementId: 'G-0C8JK5K5F8',
  );
}
